---
- include: install.yml

- name: Setting up selinux
  selinux: policy={{ selinuxpolicy }} state={{ selinuxstate }}
  when: ansible_os_family == 'RedHat'

- name: sestatus
  command: sestatus
  register: out

- debug: var=out.stdout_lines
