---
- name: Load the variable
  include_vars: '{{ ansible_os_family }}.yml'
- name: SSHD HARD
  lineinfile: dest=/etc/ssh/sshd_config regexp="^{{ item.name }} " line:"{{ item.name }} {{ item.value }}"
  with_items:
    - { name: 'Protocole',      value:'2'}

- name:
  service: name='{{ sshd }}' stated= restarted   
